// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1nEcg3pKIgnD1KvOSbO4RXX-JC2528qc',
    appId: '1:98593418263:web:9e935b36befdff360f0052',
    messagingSenderId: '98593418263',
    projectId: 'fresh-remedy-app',
    authDomain: 'fresh-remedy-app.firebaseapp.com',
    storageBucket: 'fresh-remedy-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSBn_wsbA0UhS5i1T19sojf9DxQOv17q8',
    appId: '1:98593418263:android:757264d2fd894abd0f0052',
    messagingSenderId: '98593418263',
    projectId: 'fresh-remedy-app',
    storageBucket: 'fresh-remedy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcphwLhHNsj-RgQCrVoxBIDZlcllU4RQo',
    appId: '1:98593418263:ios:122f51fd713a125a0f0052',
    messagingSenderId: '98593418263',
    projectId: 'fresh-remedy-app',
    storageBucket: 'fresh-remedy-app.firebasestorage.app',
    iosBundleId: 'com.example.fresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcphwLhHNsj-RgQCrVoxBIDZlcllU4RQo',
    appId: '1:98593418263:ios:122f51fd713a125a0f0052',
    messagingSenderId: '98593418263',
    projectId: 'fresh-remedy-app',
    storageBucket: 'fresh-remedy-app.firebasestorage.app',
    iosBundleId: 'com.example.fresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1nEcg3pKIgnD1KvOSbO4RXX-JC2528qc',
    appId: '1:98593418263:web:7ad966e5cbe9f8dc0f0052',
    messagingSenderId: '98593418263',
    projectId: 'fresh-remedy-app',
    authDomain: 'fresh-remedy-app.firebaseapp.com',
    storageBucket: 'fresh-remedy-app.firebasestorage.app',
  );

}